python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 0
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 1
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 2
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 3
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 4
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 5
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 6
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 7
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 8
python3 /home/ubuntu/RecSysChallenge2024/src/polimi/test/catboost_batch_training.py -batch 9